POST http://localhost:3000/user-api/register
Content-Type: application/json

{
    "username": "test",
    "firstName": "test",
    "email": "test@test.in",
    "password": "test",
    "user-age":18,
    "user-genre" : ["horror","comedy","action"],
    "article-id":[]
}
###
POST https://backend-nextpad.vercel.app/user-api/login
Content-Type: application/json

{
    "username": "ppp",
    "password": "ppp"
}
###
POST http://localhost:5000/user-api/login
Content-Type: application/json

{
    "username": "ppp",
    "password": "ppp"
}   



###
POST https://potential-space-potato-9vr44vj9jpq36qw-3000.app.github.dev/user-api/new-article
Content-Type: application/json

{
    "articleId": {{$timestamp}} ,
    "articleName": "Urban Legends",
    "articleDescription": "Urban legends are contemporary folklore that are told as true stories. Learn about urban legends and read about urban legends at HowStuffWorks.",
    "content":"lorem ipsum dolor sit amet consectetur adipiscing elit. Nulla nec purus feugiat, vestibulum nunc id, tincidunt nunc . lorem30",   
    "username" : "test",
    "genre":["Action"],
    "keywords":["horror","urban legends","folklore","scary stories","ghost stories","urban myths"],
    "rating":8,
    "ageGroup":"12-18",
    "visibility":true,
    "comments":[
        {
            "username":"karthikeya",
            "text":"worst"
        },
        {
            "username":"praneesh",
            "text":"Best"
        }
    ]
    
}

###
PUT http://localhost:3000/user-api/modify-article
Content-Type: application/json

{
    "articleId": 1711098602 ,
    "articleName": "fuckin Legends",
    "articleDescription": "Urban legends are contemporary folklore that are told as true stories. Learn about urban legends and read about urban legends at HowStuffWorks.",
    "content":"lorem ipsum dolor sit amet consectetur adipiscing elit. Nulla nec purus feugiat, vestibulum nunc id, tincidunt nunc . lorem30",   
    "username" : "test",
    "genre":["horror"],
    "keywords":["horror","urban legends","folklore","scary stories","ghost stories","urban myths"],
    "rating":8,
    "ageGroup":"12-18",
    "visibility":true,
    "comments":[
        {
            "username":"karthikeya",
            "text":"worst"
        },
        {
            "username":"praneesh",
            "text":"Best"
        }
    ]
    
}
###

GET http://localhost:5000/user-api/home

###

GET https://potential-space-potato-9vr44vj9jpq36qw-3000.app.github.dev/user-api/home/42220561-c35d-43bf-a7dd-5b3a7d929aa3

###
POST http://localhost:3000/user-api/comment/1711098738
Content-Type: application/json

{
    "username":"test",
    "text":"broo burra pichekki"
}

###
PUT https://potential-space-potato-9vr44vj9jpq36qw-3000.app.github.dev/user-api/delete-article/96fed696-a6c2-402f-a3be-a54a43406469


###



GET https://potential-space-potato-9vr44vj9jpq36qw-3000.app.github.dev/user-api/user-profile/ppp